import type { EnvVariable } from './types';

/**
 * Environment variables reference database
 * Contains metadata about common environment variables
 */
export const sampleEnvVariables: EnvVariable[] = [
  // ==================== SMS & Communication ====================
  {
    name: 'TWILIO_ACCOUNT_SID',
    description: 'Twilio account SID for SMS, voice, and communication APIs. Required for all Twilio services.',
    category: 'sms',
    service: 'Twilio',
    required: true,
    example: 'AC1234567890abcdef1234567890abcdef',
    keywords: ['sms', 'voice', 'communication', 'messaging', 'twilio', 'phone', 'verification'],
    relatedTo: ['TWILIO_AUTH_TOKEN', 'TWILIO_PHONE_NUMBER'],
  },
  {
    name: 'TWILIO_AUTH_TOKEN',
    description: 'Twilio authentication token for API requests. Keep secret, never expose in frontend code.',
    category: 'sms',
    service: 'Twilio',
    required: true,
    example: 'your_auth_token_here',
    keywords: ['sms', 'voice', 'authentication', 'twilio', 'secret'],
    relatedTo: ['TWILIO_ACCOUNT_SID'],
  },
  {
    name: 'TWILIO_PHONE_NUMBER',
    description: 'Twilio phone number for sending SMS and making calls. Format: +1234567890',
    category: 'sms',
    service: 'Twilio',
    required: true,
    example: '+15551234567',
    keywords: ['sms', 'phone', 'twilio', 'sender', 'caller id'],
    relatedTo: ['TWILIO_ACCOUNT_SID', 'TWILIO_AUTH_TOKEN'],
  },
  {
    name: 'TWILIO_VERIFY_SID',
    description: 'Twilio Verify service SID for phone number verification and 2FA',
    category: 'sms',
    service: 'Twilio',
    required: false,
    example: 'VA1234567890abcdef',
    keywords: ['verification', '2fa', 'otp', 'twilio', 'phone verification'],
    relatedTo: ['TWILIO_ACCOUNT_SID'],
  },
  {
    name: 'TWILIO_API_KEY',
    description: 'Twilio API key for enhanced security. Use instead of auth token for production.',
    category: 'sms',
    service: 'Twilio',
    required: false,
    example: 'SK1234567890abcdef',
    keywords: ['api key', 'twilio', 'security', 'authentication'],
    relatedTo: ['TWILIO_API_SECRET', 'TWILIO_ACCOUNT_SID'],
  },
  {
    name: 'TWILIO_API_SECRET',
    description: 'Twilio API secret paired with API key for secure authentication',
    category: 'sms',
    service: 'Twilio',
    required: false,
    example: 'your_api_secret_here',
    keywords: ['api secret', 'twilio', 'security', 'authentication'],
    relatedTo: ['TWILIO_API_KEY'],
  },

  // ==================== Email Providers ====================
  {
    name: 'SENDGRID_API_KEY',
    description: 'SendGrid API key for transactional and marketing emails. Supports templates and analytics.',
    category: 'email',
    service: 'SendGrid',
    required: true,
    example: 'SG.xxxxxxxxxxxx',
    keywords: ['email', 'sendgrid', 'transactional', 'marketing', 'smtp', 'templates'],
    relatedTo: ['SENDGRID_FROM_EMAIL'],
  },
  {
    name: 'SENDGRID_FROM_EMAIL',
    description: 'Verified sender email address for SendGrid',
    category: 'email',
    service: 'SendGrid',
    required: false,
    example: 'noreply@yourdomain.com',
    keywords: ['email', 'sendgrid', 'sender', 'from address'],
    relatedTo: ['SENDGRID_API_KEY'],
  },
  {
    name: 'BREVO_API_KEY',
    description: 'Brevo (formerly Sendinblue) API key for email marketing and transactional emails',
    category: 'email',
    service: 'Brevo',
    required: true,
    example: 'xkeysib-xxxxxxxxxxxx',
    keywords: ['email', 'brevo', 'sendinblue', 'marketing', 'transactional', 'campaigns'],
    relatedTo: [],
  },
  {
    name: 'MAILGUN_API_KEY',
    description: 'Mailgun API key for email sending, validation, and routing',
    category: 'email',
    service: 'Mailgun',
    required: true,
    example: 'key-xxxxxxxxxxxx',
    keywords: ['email', 'mailgun', 'transactional', 'validation', 'routing'],
    relatedTo: ['MAILGUN_DOMAIN'],
  },
  {
    name: 'MAILGUN_DOMAIN',
    description: 'Mailgun domain for sending emails. Must be verified in Mailgun dashboard.',
    category: 'email',
    service: 'Mailgun',
    required: true,
    example: 'mg.yourdomain.com',
    keywords: ['email', 'mailgun', 'domain', 'sender'],
    relatedTo: ['MAILGUN_API_KEY'],
  },
  {
    name: 'RESEND_API_KEY',
    description: 'Resend API key for developer-friendly email API with React Email support',
    category: 'email',
    service: 'Resend',
    required: true,
    example: 're_xxxxxxxxxxxx',
    keywords: ['email', 'resend', 'transactional', 'react email', 'developer'],
    relatedTo: [],
  },
  {
    name: 'MAILJET_API_KEY',
    description: 'Mailjet public API key for email and SMS marketing',
    category: 'email',
    service: 'Mailjet',
    required: true,
    example: 'your_api_key',
    keywords: ['email', 'mailjet', 'marketing', 'campaigns', 'sms'],
    relatedTo: ['MAILJET_SECRET_KEY'],
  },
  {
    name: 'MAILJET_SECRET_KEY',
    description: 'Mailjet secret API key paired with public key',
    category: 'email',
    service: 'Mailjet',
    required: true,
    example: 'your_secret_key',
    keywords: ['email', 'mailjet', 'secret', 'authentication'],
    relatedTo: ['MAILJET_API_KEY'],
  },
  {
    name: 'POSTMARK_API_TOKEN',
    description: 'Postmark API token for transactional email with high deliverability',
    category: 'email',
    service: 'Postmark',
    required: true,
    example: 'xxxxxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
    keywords: ['email', 'postmark', 'transactional', 'deliverability'],
    relatedTo: [],
  },
  {
    name: 'EMAIL_ENGINE_API_KEY',
    description: 'EmailEngine API key for IMAP/SMTP email integration and automation',
    category: 'email',
    service: 'EmailEngine',
    required: false,
    example: 'ee_xxxxxxxxxxxx',
    keywords: ['email', 'imap', 'smtp', 'automation', 'integration'],
    relatedTo: [],
  },

  // ==================== SMTP Credentials ====================
  {
    name: 'SMTP_HOST',
    description: 'SMTP server hostname for direct email sending',
    category: 'email',
    service: 'SMTP',
    required: true,
    example: 'smtp.gmail.com',
    keywords: ['smtp', 'email', 'server', 'mail'],
    relatedTo: ['SMTP_PORT', 'SMTP_USER', 'SMTP_PASSWORD'],
  },
  {
    name: 'SMTP_PORT',
    description: 'SMTP server port. Common: 587 (TLS), 465 (SSL), 25 (unencrypted)',
    category: 'email',
    service: 'SMTP',
    required: true,
    example: '587',
    keywords: ['smtp', 'port', 'tls', 'ssl'],
    relatedTo: ['SMTP_HOST'],
  },
  {
    name: 'SMTP_USER',
    description: 'SMTP authentication username, usually email address',
    category: 'email',
    service: 'SMTP',
    required: true,
    example: 'your@email.com',
    keywords: ['smtp', 'user', 'authentication', 'email'],
    relatedTo: ['SMTP_PASSWORD'],
  },
  {
    name: 'SMTP_PASSWORD',
    description: 'SMTP authentication password or app-specific password',
    category: 'email',
    service: 'SMTP',
    required: true,
    example: 'your_app_password',
    keywords: ['smtp', 'password', 'authentication', 'secret'],
    relatedTo: ['SMTP_USER'],
  },
  {
    name: 'GMAIL_APP_PASSWORD',
    description: 'Gmail app-specific password for SMTP. Generate in Google Account > Security > App passwords',
    category: 'email',
    service: 'Gmail',
    required: false,
    example: 'xxxx xxxx xxxx xxxx',
    keywords: ['gmail', 'smtp', 'app password', 'google', 'email'],
    relatedTo: ['GMAIL_USER'],
  },
  {
    name: 'GMAIL_USER',
    description: 'Gmail email address for SMTP authentication',
    category: 'email',
    service: 'Gmail',
    required: false,
    example: 'your@gmail.com',
    keywords: ['gmail', 'email', 'google', 'smtp'],
    relatedTo: ['GMAIL_APP_PASSWORD'],
  },
  {
    name: 'ICLOUD_APP_PASSWORD',
    description: 'iCloud app-specific password for SMTP. Generate in Apple ID account settings.',
    category: 'email',
    service: 'iCloud',
    required: false,
    example: 'xxxx-xxxx-xxxx-xxxx',
    keywords: ['icloud', 'apple', 'smtp', 'app password', 'email'],
    relatedTo: ['ICLOUD_EMAIL'],
  },
  {
    name: 'ICLOUD_EMAIL',
    description: 'iCloud email address for SMTP authentication',
    category: 'email',
    service: 'iCloud',
    required: false,
    example: 'your@icloud.com',
    keywords: ['icloud', 'apple', 'email', 'smtp'],
    relatedTo: ['ICLOUD_APP_PASSWORD'],
  },

  // ==================== Authentication Providers ====================
  {
    name: 'AUTH0_DOMAIN',
    description: 'Auth0 tenant domain for authentication. Format: your-tenant.auth0.com',
    category: 'auth',
    service: 'Auth0',
    required: true,
    example: 'your-app.auth0.com',
    keywords: ['auth', 'auth0', 'authentication', 'identity', 'sso', 'oauth'],
    relatedTo: ['AUTH0_CLIENT_ID', 'AUTH0_CLIENT_SECRET'],
  },
  {
    name: 'AUTH0_CLIENT_ID',
    description: 'Auth0 application client ID for OAuth flows',
    category: 'auth',
    service: 'Auth0',
    required: true,
    example: 'xxxxxxxxxxxxxxxxxxxx',
    keywords: ['auth0', 'client id', 'oauth', 'authentication'],
    relatedTo: ['AUTH0_DOMAIN', 'AUTH0_CLIENT_SECRET'],
  },
  {
    name: 'AUTH0_CLIENT_SECRET',
    description: 'Auth0 application client secret. Never expose in frontend code.',
    category: 'auth',
    service: 'Auth0',
    required: true,
    example: 'xxxxxxxxxxxxxxxxxxxx',
    keywords: ['auth0', 'client secret', 'oauth', 'authentication', 'secret'],
    relatedTo: ['AUTH0_CLIENT_ID'],
  },
  {
    name: 'AUTH0_AUDIENCE',
    description: 'Auth0 API audience identifier for API authorization',
    category: 'auth',
    service: 'Auth0',
    required: false,
    example: 'https://your-api.example.com',
    keywords: ['auth0', 'audience', 'api', 'authorization'],
    relatedTo: ['AUTH0_DOMAIN'],
  },
  {
    name: 'AUTH0_MANAGEMENT_API_TOKEN',
    description: 'Auth0 Management API token for user and tenant management',
    category: 'auth',
    service: 'Auth0',
    required: false,
    example: 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9...',
    keywords: ['auth0', 'management', 'api', 'admin', 'users'],
    relatedTo: ['AUTH0_DOMAIN'],
  },
  {
    name: 'CLERK_SECRET_KEY',
    description: 'Clerk secret key for backend authentication. Use in server-side code only.',
    category: 'auth',
    service: 'Clerk',
    required: true,
    example: 'sk_test_xxxxxxxxxxxx',
    keywords: ['clerk', 'authentication', 'secret', 'backend', 'users'],
    relatedTo: ['CLERK_PUBLISHABLE_KEY'],
  },
  {
    name: 'CLERK_PUBLISHABLE_KEY',
    description: 'Clerk publishable key for frontend authentication components',
    category: 'auth',
    service: 'Clerk',
    required: true,
    example: 'pk_test_xxxxxxxxxxxx',
    keywords: ['clerk', 'authentication', 'frontend', 'public', 'users'],
    relatedTo: ['CLERK_SECRET_KEY'],
  },
  {
    name: 'CLERK_WEBHOOK_SECRET',
    description: 'Clerk webhook signing secret for secure webhook verification',
    category: 'auth',
    service: 'Clerk',
    required: false,
    example: 'whsec_xxxxxxxxxxxx',
    keywords: ['clerk', 'webhook', 'secret', 'verification'],
    relatedTo: ['CLERK_SECRET_KEY'],
  },
  {
    name: 'STACK_AUTH_SECRET',
    description: 'Stack Auth secret key for open-source authentication',
    category: 'auth',
    service: 'StackAuth',
    required: false,
    example: 'stack_xxxxxxxxxxxx',
    keywords: ['stack auth', 'authentication', 'open source', 'secret'],
    relatedTo: [],
  },
  {
    name: 'NEXTAUTH_SECRET',
    description: 'NextAuth.js secret for encrypting tokens and cookies. Generate with openssl rand -base64 32',
    category: 'auth',
    service: 'NextAuth',
    required: true,
    example: 'your-random-32-char-secret',
    keywords: ['nextauth', 'next.js', 'authentication', 'secret', 'session'],
    relatedTo: ['NEXTAUTH_URL'],
  },
  {
    name: 'NEXTAUTH_URL',
    description: 'NextAuth.js canonical URL for your application',
    category: 'auth',
    service: 'NextAuth',
    required: true,
    example: 'https://yourdomain.com',
    keywords: ['nextauth', 'next.js', 'url', 'callback'],
    relatedTo: ['NEXTAUTH_SECRET'],
  },
  {
    name: 'JWT_SECRET',
    description: 'Secret key for signing and verifying JWT tokens. Use strong random string.',
    category: 'auth',
    service: 'JWT',
    required: true,
    example: 'your-256-bit-secret',
    keywords: ['jwt', 'token', 'secret', 'authentication', 'authorization'],
    relatedTo: [],
  },

  // ==================== Google & YouTube APIs ====================
  {
    name: 'GOOGLE_CLIENT_ID',
    description: 'Google OAuth 2.0 client ID for authentication and API access',
    category: 'auth',
    service: 'Google',
    required: true,
    example: 'xxxxxxxxxxxx.apps.googleusercontent.com',
    keywords: ['google', 'oauth', 'authentication', 'client id', 'login'],
    relatedTo: ['GOOGLE_CLIENT_SECRET'],
  },
  {
    name: 'GOOGLE_CLIENT_SECRET',
    description: 'Google OAuth 2.0 client secret. Keep secure, never expose publicly.',
    category: 'auth',
    service: 'Google',
    required: true,
    example: 'GOCSPX-xxxxxxxxxxxx',
    keywords: ['google', 'oauth', 'secret', 'authentication'],
    relatedTo: ['GOOGLE_CLIENT_ID'],
  },
  {
    name: 'GOOGLE_API_KEY',
    description: 'Google API key for accessing Google services without user auth (Maps, Places, etc.)',
    category: 'other',
    service: 'Google',
    required: false,
    example: 'AIzaxxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['google', 'api key', 'maps', 'places', 'services'],
    relatedTo: ['GOOGLE_MAPS_API_KEY'],
  },
  {
    name: 'GOOGLE_MAPS_API_KEY',
    description: 'Google Maps Platform API key for maps, places, geocoding, and directions',
    category: 'other',
    service: 'Google Maps',
    required: false,
    example: 'AIzaxxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['google maps', 'geocoding', 'places', 'directions', 'maps'],
    relatedTo: ['GOOGLE_API_KEY'],
  },
  {
    name: 'YOUTUBE_API_KEY',
    description: 'YouTube Data API v3 key for video search, channels, and playlists',
    category: 'other',
    service: 'YouTube',
    required: false,
    example: 'AIzaxxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['youtube', 'video', 'api', 'search', 'channels', 'playlists'],
    relatedTo: ['GOOGLE_API_KEY'],
  },
  {
    name: 'GOOGLE_SERVICE_ACCOUNT_KEY',
    description: 'Google Cloud service account JSON key for server-to-server authentication',
    category: 'deployment',
    service: 'Google Cloud',
    required: false,
    example: '{"type":"service_account","project_id":"..."}',
    keywords: ['google cloud', 'service account', 'gcp', 'authentication'],
    relatedTo: ['GOOGLE_PROJECT_ID'],
  },
  {
    name: 'GOOGLE_PROJECT_ID',
    description: 'Google Cloud project ID for resource management',
    category: 'deployment',
    service: 'Google Cloud',
    required: false,
    example: 'my-project-123456',
    keywords: ['google cloud', 'gcp', 'project', 'resources'],
    relatedTo: ['GOOGLE_SERVICE_ACCOUNT_KEY'],
  },
  {
    name: 'GOOGLE_APPLICATION_CREDENTIALS',
    description: 'Path to Google Cloud service account JSON key file',
    category: 'deployment',
    service: 'Google Cloud',
    required: false,
    example: '/path/to/service-account.json',
    keywords: ['google cloud', 'credentials', 'service account', 'gcp'],
    relatedTo: ['GOOGLE_SERVICE_ACCOUNT_KEY'],
  },

  // ==================== Social Platforms ====================
  {
    name: 'TELEGRAM_BOT_TOKEN',
    description: 'Telegram Bot API token from @BotFather for bot commands and messages',
    category: 'social',
    service: 'Telegram',
    required: true,
    example: '123456789:ABCdefGHIjklMNOpqrSTUvwxYZ',
    keywords: ['telegram', 'bot', 'messaging', 'chat', 'automation'],
    relatedTo: ['TELEGRAM_CHAT_ID'],
  },
  {
    name: 'TELEGRAM_CHAT_ID',
    description: 'Telegram chat or channel ID for sending messages',
    category: 'social',
    service: 'Telegram',
    required: false,
    example: '-1001234567890',
    keywords: ['telegram', 'chat', 'channel', 'messaging'],
    relatedTo: ['TELEGRAM_BOT_TOKEN'],
  },
  {
    name: 'TWITTER_API_KEY',
    description: 'Twitter/X API key (consumer key) for OAuth 1.0a authentication',
    category: 'social',
    service: 'Twitter',
    required: true,
    example: 'xxxxxxxxxxxxxxxxxxxx',
    keywords: ['twitter', 'x', 'social', 'api', 'oauth'],
    relatedTo: ['TWITTER_API_SECRET', 'TWITTER_ACCESS_TOKEN'],
  },
  {
    name: 'TWITTER_API_SECRET',
    description: 'Twitter/X API secret (consumer secret) for OAuth authentication',
    category: 'social',
    service: 'Twitter',
    required: true,
    example: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['twitter', 'x', 'secret', 'oauth'],
    relatedTo: ['TWITTER_API_KEY'],
  },
  {
    name: 'TWITTER_ACCESS_TOKEN',
    description: 'Twitter/X user access token for posting and account actions',
    category: 'social',
    service: 'Twitter',
    required: false,
    example: '1234567890-xxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['twitter', 'x', 'access token', 'user'],
    relatedTo: ['TWITTER_ACCESS_TOKEN_SECRET'],
  },
  {
    name: 'TWITTER_ACCESS_TOKEN_SECRET',
    description: 'Twitter/X user access token secret',
    category: 'social',
    service: 'Twitter',
    required: false,
    example: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['twitter', 'x', 'secret', 'access token'],
    relatedTo: ['TWITTER_ACCESS_TOKEN'],
  },
  {
    name: 'TWITTER_BEARER_TOKEN',
    description: 'Twitter/X API v2 bearer token for app-only authentication',
    category: 'social',
    service: 'Twitter',
    required: false,
    example: 'AAAAAAAAAAAAAAAAAAAAAxxxxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['twitter', 'x', 'bearer', 'api v2', 'app only'],
    relatedTo: ['TWITTER_API_KEY'],
  },
  {
    name: 'REDDIT_CLIENT_ID',
    description: 'Reddit API client ID from reddit.com/prefs/apps',
    category: 'social',
    service: 'Reddit',
    required: true,
    example: 'xxxxxxxxxxxx',
    keywords: ['reddit', 'social', 'api', 'oauth'],
    relatedTo: ['REDDIT_CLIENT_SECRET'],
  },
  {
    name: 'REDDIT_CLIENT_SECRET',
    description: 'Reddit API client secret for OAuth authentication',
    category: 'social',
    service: 'Reddit',
    required: true,
    example: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['reddit', 'secret', 'oauth'],
    relatedTo: ['REDDIT_CLIENT_ID'],
  },
  {
    name: 'REDDIT_USER_AGENT',
    description: 'Reddit API user agent string (required by Reddit API)',
    category: 'social',
    service: 'Reddit',
    required: true,
    example: 'MyApp/1.0 by /u/username',
    keywords: ['reddit', 'user agent', 'api'],
    relatedTo: ['REDDIT_CLIENT_ID'],
  },
  {
    name: 'META_ACCESS_TOKEN',
    description: 'Meta (Facebook/Instagram) Graph API access token',
    category: 'social',
    service: 'Meta',
    required: true,
    example: 'EAAxxxxxxxxxxxxxxxx',
    keywords: ['meta', 'facebook', 'instagram', 'graph api', 'social'],
    relatedTo: ['META_APP_ID', 'META_APP_SECRET'],
  },
  {
    name: 'META_APP_ID',
    description: 'Meta app ID from developers.facebook.com',
    category: 'social',
    service: 'Meta',
    required: true,
    example: '1234567890123456',
    keywords: ['meta', 'facebook', 'app id', 'social'],
    relatedTo: ['META_APP_SECRET'],
  },
  {
    name: 'META_APP_SECRET',
    description: 'Meta app secret for server-side authentication',
    category: 'social',
    service: 'Meta',
    required: true,
    example: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['meta', 'facebook', 'secret', 'authentication'],
    relatedTo: ['META_APP_ID'],
  },
  {
    name: 'DISCORD_BOT_TOKEN',
    description: 'Discord bot token from Discord Developer Portal',
    category: 'social',
    service: 'Discord',
    required: true,
    example: 'MTxxxxxxxxxx.xxxxxx.xxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['discord', 'bot', 'chat', 'messaging', 'community'],
    relatedTo: ['DISCORD_CLIENT_ID'],
  },
  {
    name: 'DISCORD_CLIENT_ID',
    description: 'Discord application client ID for OAuth2',
    category: 'social',
    service: 'Discord',
    required: false,
    example: '123456789012345678',
    keywords: ['discord', 'oauth', 'client id', 'authentication'],
    relatedTo: ['DISCORD_CLIENT_SECRET'],
  },
  {
    name: 'DISCORD_CLIENT_SECRET',
    description: 'Discord application client secret for OAuth2',
    category: 'social',
    service: 'Discord',
    required: false,
    example: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['discord', 'oauth', 'secret'],
    relatedTo: ['DISCORD_CLIENT_ID'],
  },
  {
    name: 'DISCORD_WEBHOOK_URL',
    description: 'Discord webhook URL for sending messages to channels',
    category: 'social',
    service: 'Discord',
    required: false,
    example: 'https://discord.com/api/webhooks/123456/xxxxx',
    keywords: ['discord', 'webhook', 'notifications', 'messages'],
    relatedTo: ['DISCORD_BOT_TOKEN'],
  },
  {
    name: 'SLACK_BOT_TOKEN',
    description: 'Slack bot token (xoxb-) for sending messages and bot interactions',
    category: 'social',
    service: 'Slack',
    required: true,
    example: 'xoxb-xxxxxxxxxxxx-xxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['slack', 'bot', 'messaging', 'workspace', 'notifications'],
    relatedTo: ['SLACK_SIGNING_SECRET'],
  },
  {
    name: 'SLACK_SIGNING_SECRET',
    description: 'Slack app signing secret for verifying webhook requests',
    category: 'social',
    service: 'Slack',
    required: false,
    example: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['slack', 'webhook', 'security', 'verification'],
    relatedTo: ['SLACK_BOT_TOKEN'],
  },
  {
    name: 'SLACK_WEBHOOK_URL',
    description: 'Slack incoming webhook URL for posting messages',
    category: 'social',
    service: 'Slack',
    required: false,
    example: 'https://hooks.slack.com/services/T00/B00/xxxxx',
    keywords: ['slack', 'webhook', 'notifications', 'messages'],
    relatedTo: ['SLACK_BOT_TOKEN'],
  },

  // ==================== CMS & Content ====================
  {
    name: 'NOTION_API_KEY',
    description: 'Notion internal integration token for database and page access',
    category: 'cms',
    service: 'Notion',
    required: true,
    example: 'secret_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['notion', 'database', 'pages', 'content', 'workspace'],
    relatedTo: ['NOTION_DATABASE_ID'],
  },
  {
    name: 'NOTION_DATABASE_ID',
    description: 'Notion database ID for specific database operations',
    category: 'cms',
    service: 'Notion',
    required: false,
    example: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['notion', 'database', 'content'],
    relatedTo: ['NOTION_API_KEY'],
  },
  {
    name: 'CONTENTFUL_SPACE_ID',
    description: 'Contentful space ID for content management',
    category: 'cms',
    service: 'Contentful',
    required: true,
    example: 'xxxxxxxxxxxx',
    keywords: ['contentful', 'cms', 'content', 'headless'],
    relatedTo: ['CONTENTFUL_ACCESS_TOKEN'],
  },
  {
    name: 'CONTENTFUL_ACCESS_TOKEN',
    description: 'Contentful Content Delivery API access token',
    category: 'cms',
    service: 'Contentful',
    required: true,
    example: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['contentful', 'api', 'content', 'delivery'],
    relatedTo: ['CONTENTFUL_SPACE_ID'],
  },
  {
    name: 'CONTENTFUL_MANAGEMENT_TOKEN',
    description: 'Contentful Content Management API token for write operations',
    category: 'cms',
    service: 'Contentful',
    required: false,
    example: 'CFPAT-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['contentful', 'management', 'cms', 'write'],
    relatedTo: ['CONTENTFUL_SPACE_ID'],
  },
  {
    name: 'SANITY_PROJECT_ID',
    description: 'Sanity.io project ID for content management',
    category: 'cms',
    service: 'Sanity',
    required: true,
    example: 'xxxxxxxxxxxx',
    keywords: ['sanity', 'cms', 'content', 'headless'],
    relatedTo: ['SANITY_TOKEN'],
  },
  {
    name: 'SANITY_TOKEN',
    description: 'Sanity.io API token for read/write operations',
    category: 'cms',
    service: 'Sanity',
    required: false,
    example: 'skxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['sanity', 'api', 'token', 'content'],
    relatedTo: ['SANITY_PROJECT_ID'],
  },
  {
    name: 'STRAPI_API_TOKEN',
    description: 'Strapi API token for headless CMS access',
    category: 'cms',
    service: 'Strapi',
    required: true,
    example: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['strapi', 'cms', 'api', 'headless', 'content'],
    relatedTo: ['STRAPI_URL'],
  },
  {
    name: 'STRAPI_URL',
    description: 'Strapi instance URL for API calls',
    category: 'cms',
    service: 'Strapi',
    required: true,
    example: 'https://your-strapi.herokuapp.com',
    keywords: ['strapi', 'url', 'cms', 'api'],
    relatedTo: ['STRAPI_API_TOKEN'],
  },

  // ==================== Analytics & Monitoring ====================
  {
    name: 'AMPLITUDE_API_KEY',
    description: 'Amplitude analytics API key for product analytics and user tracking',
    category: 'analytics',
    service: 'Amplitude',
    required: true,
    example: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['amplitude', 'analytics', 'product', 'tracking', 'events'],
    relatedTo: ['AMPLITUDE_SECRET_KEY'],
  },
  {
    name: 'AMPLITUDE_SECRET_KEY',
    description: 'Amplitude secret key for server-side event tracking',
    category: 'analytics',
    service: 'Amplitude',
    required: false,
    example: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['amplitude', 'secret', 'server', 'analytics'],
    relatedTo: ['AMPLITUDE_API_KEY'],
  },
  {
    name: 'SENTRY_DSN',
    description: 'Sentry Data Source Name for error tracking and performance monitoring',
    category: 'monitoring',
    service: 'Sentry',
    required: true,
    example: 'https://xxxx@o123.ingest.sentry.io/456',
    keywords: ['sentry', 'error tracking', 'monitoring', 'debugging', 'performance'],
    relatedTo: ['SENTRY_AUTH_TOKEN'],
  },
  {
    name: 'SENTRY_AUTH_TOKEN',
    description: 'Sentry authentication token for release management and source maps',
    category: 'monitoring',
    service: 'Sentry',
    required: false,
    example: 'sntrys_xxxxxxxxxxxx',
    keywords: ['sentry', 'auth', 'releases', 'source maps'],
    relatedTo: ['SENTRY_DSN'],
  },
  {
    name: 'SENTRY_ORG',
    description: 'Sentry organization slug for project management',
    category: 'monitoring',
    service: 'Sentry',
    required: false,
    example: 'my-org',
    keywords: ['sentry', 'organization', 'project'],
    relatedTo: ['SENTRY_DSN'],
  },
  {
    name: 'SENTRY_PROJECT',
    description: 'Sentry project slug for error grouping',
    category: 'monitoring',
    service: 'Sentry',
    required: false,
    example: 'my-project',
    keywords: ['sentry', 'project', 'errors'],
    relatedTo: ['SENTRY_DSN'],
  },
  {
    name: 'DATADOG_API_KEY',
    description: 'Datadog API key for metrics, logs, and APM',
    category: 'monitoring',
    service: 'Datadog',
    required: true,
    example: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['datadog', 'monitoring', 'metrics', 'logs', 'apm'],
    relatedTo: ['DATADOG_APP_KEY'],
  },
  {
    name: 'DATADOG_APP_KEY',
    description: 'Datadog application key for dashboard and query access',
    category: 'monitoring',
    service: 'Datadog',
    required: false,
    example: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['datadog', 'application', 'dashboard', 'queries'],
    relatedTo: ['DATADOG_API_KEY'],
  },
  {
    name: 'GOOGLE_ANALYTICS_ID',
    description: 'Google Analytics 4 measurement ID for web analytics',
    category: 'analytics',
    service: 'Google Analytics',
    required: false,
    example: 'G-XXXXXXXXXX',
    keywords: ['google analytics', 'ga4', 'tracking', 'web analytics'],
    relatedTo: [],
  },
  {
    name: 'MIXPANEL_TOKEN',
    description: 'Mixpanel project token for product analytics',
    category: 'analytics',
    service: 'Mixpanel',
    required: false,
    example: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['mixpanel', 'analytics', 'product', 'events', 'tracking'],
    relatedTo: ['MIXPANEL_API_SECRET'],
  },
  {
    name: 'MIXPANEL_API_SECRET',
    description: 'Mixpanel API secret for server-side event tracking',
    category: 'analytics',
    service: 'Mixpanel',
    required: false,
    example: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['mixpanel', 'secret', 'server', 'analytics'],
    relatedTo: ['MIXPANEL_TOKEN'],
  },
  {
    name: 'POSTHOG_API_KEY',
    description: 'PostHog API key for product analytics and feature flags',
    category: 'analytics',
    service: 'PostHog',
    required: false,
    example: 'phc_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['posthog', 'analytics', 'feature flags', 'product'],
    relatedTo: ['POSTHOG_HOST'],
  },
  {
    name: 'POSTHOG_HOST',
    description: 'PostHog instance host URL',
    category: 'analytics',
    service: 'PostHog',
    required: false,
    example: 'https://app.posthog.com',
    keywords: ['posthog', 'host', 'url'],
    relatedTo: ['POSTHOG_API_KEY'],
  },
  {
    name: 'LOGROCKET_APP_ID',
    description: 'LogRocket application ID for session replay and debugging',
    category: 'monitoring',
    service: 'LogRocket',
    required: false,
    example: 'xxxxx/your-app',
    keywords: ['logrocket', 'session replay', 'debugging', 'monitoring'],
    relatedTo: [],
  },

  // ==================== Payment Processing ====================
  {
    name: 'STRIPE_SECRET_KEY',
    description: 'Stripe secret API key for payment processing. Never expose in frontend.',
    category: 'payment',
    service: 'Stripe',
    required: true,
    example: 'sk_test_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['stripe', 'payment', 'billing', 'subscription', 'secret'],
    relatedTo: ['STRIPE_PUBLISHABLE_KEY', 'STRIPE_WEBHOOK_SECRET'],
  },
  {
    name: 'STRIPE_PUBLISHABLE_KEY',
    description: 'Stripe publishable key for frontend payment forms',
    category: 'payment',
    service: 'Stripe',
    required: true,
    example: 'pk_test_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['stripe', 'payment', 'frontend', 'public'],
    relatedTo: ['STRIPE_SECRET_KEY'],
  },
  {
    name: 'STRIPE_WEBHOOK_SECRET',
    description: 'Stripe webhook signing secret for verifying webhook events',
    category: 'payment',
    service: 'Stripe',
    required: false,
    example: 'whsec_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['stripe', 'webhook', 'security', 'events'],
    relatedTo: ['STRIPE_SECRET_KEY'],
  },
  {
    name: 'PAYPAL_CLIENT_ID',
    description: 'PayPal REST API client ID for payment integration',
    category: 'payment',
    service: 'PayPal',
    required: true,
    example: 'AXxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['paypal', 'payment', 'checkout', 'client id'],
    relatedTo: ['PAYPAL_CLIENT_SECRET'],
  },
  {
    name: 'PAYPAL_CLIENT_SECRET',
    description: 'PayPal REST API client secret for server-side authentication',
    category: 'payment',
    service: 'PayPal',
    required: true,
    example: 'ELxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['paypal', 'payment', 'secret', 'authentication'],
    relatedTo: ['PAYPAL_CLIENT_ID'],
  },
  {
    name: 'SUMUP_API_KEY',
    description: 'SumUp API key for payment processing and checkout',
    category: 'payment',
    service: 'SumUp',
    required: false,
    example: 'sup_sk_xxxxxxxxxxxx',
    keywords: ['sumup', 'payment', 'checkout', 'card payments'],
    relatedTo: ['SUMUP_MERCHANT_CODE'],
  },
  {
    name: 'SUMUP_MERCHANT_CODE',
    description: 'SumUp merchant code for identifying your business',
    category: 'payment',
    service: 'SumUp',
    required: false,
    example: 'MXXXXXXXXX',
    keywords: ['sumup', 'merchant', 'business'],
    relatedTo: ['SUMUP_API_KEY'],
  },

  // ==================== AI Services ====================
  {
    name: 'OPENAI_API_KEY',
    description: 'OpenAI API key for GPT models, embeddings, DALL-E, and Whisper',
    category: 'ai_services',
    service: 'OpenAI',
    required: true,
    example: 'sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['openai', 'gpt', 'ai', 'chat', 'embeddings', 'dalle', 'whisper'],
    relatedTo: ['OPENAI_ORG_ID'],
  },
  {
    name: 'OPENAI_ORG_ID',
    description: 'OpenAI organization ID for team billing and rate limits',
    category: 'ai_services',
    service: 'OpenAI',
    required: false,
    example: 'org-xxxxxxxxxxxxxxxxxxxx',
    keywords: ['openai', 'organization', 'billing', 'team'],
    relatedTo: ['OPENAI_API_KEY'],
  },
  {
    name: 'ANTHROPIC_API_KEY',
    description: 'Anthropic API key for Claude AI models (Sonnet, Opus, Haiku)',
    category: 'ai_services',
    service: 'Anthropic',
    required: false,
    example: 'sk-ant-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['anthropic', 'claude', 'ai', 'chat', 'reasoning'],
    relatedTo: [],
  },
  {
    name: 'GROQ_API_KEY',
    description: 'Groq API key for fast LLM inference with Llama and Mixtral models',
    category: 'ai_services',
    service: 'Groq',
    required: false,
    example: 'gsk_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['groq', 'llama', 'mixtral', 'fast inference', 'ai'],
    relatedTo: [],
  },
  {
    name: 'REPLICATE_API_TOKEN',
    description: 'Replicate API token for running open-source ML models',
    category: 'ai_services',
    service: 'Replicate',
    required: false,
    example: 'r8_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['replicate', 'ml models', 'ai', 'inference', 'stable diffusion'],
    relatedTo: [],
  },
  {
    name: 'HUGGINGFACE_API_KEY',
    description: 'Hugging Face API key for inference API and model hub access',
    category: 'ai_services',
    service: 'Hugging Face',
    required: false,
    example: 'hf_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['huggingface', 'transformers', 'ml', 'models', 'inference'],
    relatedTo: [],
  },
  {
    name: 'TOGETHER_API_KEY',
    description: 'Together AI API key for open-source model inference',
    category: 'ai_services',
    service: 'Together AI',
    required: false,
    example: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['together', 'ai', 'inference', 'llama', 'open source'],
    relatedTo: [],
  },
  {
    name: 'PERPLEXITY_API_KEY',
    description: 'Perplexity AI API key for search-augmented language models',
    category: 'ai_services',
    service: 'Perplexity',
    required: false,
    example: 'pplx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['perplexity', 'search', 'ai', 'rag', 'llm'],
    relatedTo: [],
  },
  {
    name: 'COHERE_API_KEY',
    description: 'Cohere API key for embeddings, reranking, and generation',
    category: 'ai_services',
    service: 'Cohere',
    required: false,
    example: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['cohere', 'embeddings', 'reranking', 'generation', 'ai'],
    relatedTo: [],
  },
  {
    name: 'ELEVENLABS_API_KEY',
    description: 'ElevenLabs API key for AI voice synthesis and text-to-speech',
    category: 'ai_services',
    service: 'ElevenLabs',
    required: false,
    example: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['elevenlabs', 'voice', 'tts', 'text to speech', 'ai'],
    relatedTo: [],
  },

  // ==================== Browser Automation ====================
  {
    name: 'BROWSERBASE_API_KEY',
    description: 'Browserbase API key for cloud-hosted browser automation',
    category: 'browser_automation',
    service: 'Browserbase',
    required: false,
    example: 'bb_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['browserbase', 'browser', 'automation', 'scraping', 'headless'],
    relatedTo: ['BROWSERBASE_PROJECT_ID'],
  },
  {
    name: 'BROWSERBASE_PROJECT_ID',
    description: 'Browserbase project ID for workspace organization',
    category: 'browser_automation',
    service: 'Browserbase',
    required: false,
    example: 'proj_xxxxxxxxxxxx',
    keywords: ['browserbase', 'project', 'workspace'],
    relatedTo: ['BROWSERBASE_API_KEY'],
  },
  {
    name: 'E2B_API_KEY',
    description: 'E2B API key for secure sandboxed code execution environments',
    category: 'browser_automation',
    service: 'E2B',
    required: false,
    example: 'e2b_xxxxxxxxxxxx',
    keywords: ['e2b', 'sandbox', 'code execution', 'security'],
    relatedTo: [],
  },
  {
    name: 'PLAYWRIGHT_BROWSERS_PATH',
    description: 'Path to Playwright browser binaries for E2E testing',
    category: 'browser_automation',
    service: 'Playwright',
    required: false,
    example: '/usr/local/share/playwright',
    keywords: ['playwright', 'browsers', 'testing', 'e2e'],
    relatedTo: [],
  },
  {
    name: 'PUPPETEER_EXECUTABLE_PATH',
    description: 'Path to Chrome/Chromium executable for Puppeteer',
    category: 'browser_automation',
    service: 'Puppeteer',
    required: false,
    example: '/usr/bin/chromium-browser',
    keywords: ['puppeteer', 'chrome', 'chromium', 'automation'],
    relatedTo: [],
  },

  // ==================== Database ====================
  {
    name: 'DATABASE_URL',
    description: 'Primary database connection URL with credentials',
    category: 'database',
    service: 'PostgreSQL',
    required: true,
    example: 'postgresql://user:pass@host:5432/dbname',
    keywords: ['database', 'postgres', 'postgresql', 'connection', 'sql'],
    relatedTo: ['DIRECT_URL'],
  },
  {
    name: 'DIRECT_URL',
    description: 'Direct database connection URL for migrations (bypasses connection pooling)',
    category: 'database',
    service: 'PostgreSQL',
    required: false,
    example: 'postgresql://user:pass@host:5432/dbname',
    keywords: ['database', 'direct', 'migrations', 'prisma'],
    relatedTo: ['DATABASE_URL'],
  },
  {
    name: 'REDIS_URL',
    description: 'Redis connection URL for caching and session storage',
    category: 'database',
    service: 'Redis',
    required: false,
    example: 'redis://user:pass@host:6379/0',
    keywords: ['redis', 'cache', 'session', 'memory'],
    relatedTo: [],
  },
  {
    name: 'MONGODB_URI',
    description: 'MongoDB connection URI with authentication',
    category: 'database',
    service: 'MongoDB',
    required: false,
    example: 'mongodb+srv://user:pass@cluster.mongodb.net/dbname',
    keywords: ['mongodb', 'nosql', 'document', 'database'],
    relatedTo: [],
  },
  {
    name: 'SUPABASE_URL',
    description: 'Supabase project URL for database and auth',
    category: 'database',
    service: 'Supabase',
    required: false,
    example: 'https://xxxxxxxxxxxx.supabase.co',
    keywords: ['supabase', 'database', 'postgres', 'auth'],
    relatedTo: ['SUPABASE_ANON_KEY', 'SUPABASE_SERVICE_ROLE_KEY'],
  },
  {
    name: 'SUPABASE_ANON_KEY',
    description: 'Supabase anonymous key for public client access',
    category: 'database',
    service: 'Supabase',
    required: false,
    example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
    keywords: ['supabase', 'anon', 'public', 'client'],
    relatedTo: ['SUPABASE_URL'],
  },
  {
    name: 'SUPABASE_SERVICE_ROLE_KEY',
    description: 'Supabase service role key for admin operations (never expose in frontend)',
    category: 'database',
    service: 'Supabase',
    required: false,
    example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
    keywords: ['supabase', 'service', 'admin', 'server'],
    relatedTo: ['SUPABASE_URL'],
  },
  {
    name: 'NEON_DATABASE_URL',
    description: 'Neon serverless PostgreSQL connection URL',
    category: 'database',
    service: 'Neon',
    required: false,
    example: 'postgresql://user:pass@ep-xxx.us-east-1.aws.neon.tech/dbname',
    keywords: ['neon', 'postgres', 'serverless', 'database'],
    relatedTo: [],
  },
  {
    name: 'PLANETSCALE_DATABASE_URL',
    description: 'PlanetScale MySQL-compatible serverless database URL',
    category: 'database',
    service: 'PlanetScale',
    required: false,
    example: 'mysql://user:pass@aws.connect.psdb.cloud/dbname',
    keywords: ['planetscale', 'mysql', 'serverless', 'database'],
    relatedTo: [],
  },
  {
    name: 'TURSO_DATABASE_URL',
    description: 'Turso libSQL database URL for edge SQLite',
    category: 'database',
    service: 'Turso',
    required: false,
    example: 'libsql://your-db-name.turso.io',
    keywords: ['turso', 'sqlite', 'libsql', 'edge', 'database'],
    relatedTo: ['TURSO_AUTH_TOKEN'],
  },
  {
    name: 'TURSO_AUTH_TOKEN',
    description: 'Turso authentication token for database access',
    category: 'database',
    service: 'Turso',
    required: false,
    example: 'eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9...',
    keywords: ['turso', 'auth', 'token', 'database'],
    relatedTo: ['TURSO_DATABASE_URL'],
  },
  {
    name: 'UPSTASH_REDIS_REST_URL',
    description: 'Upstash Redis REST API URL for serverless Redis',
    category: 'database',
    service: 'Upstash',
    required: false,
    example: 'https://xxxx.upstash.io',
    keywords: ['upstash', 'redis', 'serverless', 'cache'],
    relatedTo: ['UPSTASH_REDIS_REST_TOKEN'],
  },
  {
    name: 'UPSTASH_REDIS_REST_TOKEN',
    description: 'Upstash Redis REST API authentication token',
    category: 'database',
    service: 'Upstash',
    required: false,
    example: 'AXxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['upstash', 'redis', 'token', 'auth'],
    relatedTo: ['UPSTASH_REDIS_REST_URL'],
  },

  // ==================== Storage ====================
  {
    name: 'AWS_ACCESS_KEY_ID',
    description: 'AWS access key ID for S3 and other AWS services',
    category: 'storage',
    service: 'AWS',
    required: true,
    example: 'AKIAIOSFODNN7EXAMPLE',
    keywords: ['aws', 's3', 'storage', 'cloud', 'access key'],
    relatedTo: ['AWS_SECRET_ACCESS_KEY', 'AWS_REGION'],
  },
  {
    name: 'AWS_SECRET_ACCESS_KEY',
    description: 'AWS secret access key for authentication',
    category: 'storage',
    service: 'AWS',
    required: true,
    example: 'wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY',
    keywords: ['aws', 's3', 'secret', 'authentication'],
    relatedTo: ['AWS_ACCESS_KEY_ID'],
  },
  {
    name: 'AWS_REGION',
    description: 'AWS region for service endpoints',
    category: 'storage',
    service: 'AWS',
    required: true,
    example: 'us-east-1',
    keywords: ['aws', 'region', 'location'],
    relatedTo: ['AWS_ACCESS_KEY_ID'],
  },
  {
    name: 'AWS_S3_BUCKET',
    description: 'AWS S3 bucket name for file storage',
    category: 'storage',
    service: 'AWS',
    required: false,
    example: 'my-app-uploads',
    keywords: ['aws', 's3', 'bucket', 'storage'],
    relatedTo: ['AWS_ACCESS_KEY_ID'],
  },
  {
    name: 'CLOUDFLARE_R2_ACCESS_KEY',
    description: 'Cloudflare R2 access key for S3-compatible object storage',
    category: 'storage',
    service: 'Cloudflare',
    required: false,
    example: 'xxxxxxxxxxxxxxxxxxxx',
    keywords: ['cloudflare', 'r2', 's3', 'object storage'],
    relatedTo: ['CLOUDFLARE_R2_SECRET_KEY', 'CLOUDFLARE_R2_BUCKET'],
  },
  {
    name: 'CLOUDFLARE_R2_SECRET_KEY',
    description: 'Cloudflare R2 secret key for authentication',
    category: 'storage',
    service: 'Cloudflare',
    required: false,
    example: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['cloudflare', 'r2', 'secret', 'authentication'],
    relatedTo: ['CLOUDFLARE_R2_ACCESS_KEY'],
  },
  {
    name: 'CLOUDFLARE_R2_BUCKET',
    description: 'Cloudflare R2 bucket name for object storage',
    category: 'storage',
    service: 'Cloudflare',
    required: false,
    example: 'my-bucket',
    keywords: ['cloudflare', 'r2', 'bucket', 'storage'],
    relatedTo: ['CLOUDFLARE_R2_ACCESS_KEY'],
  },
  {
    name: 'UPLOADTHING_SECRET',
    description: 'UploadThing secret key for file uploads',
    category: 'storage',
    service: 'UploadThing',
    required: false,
    example: 'sk_live_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['uploadthing', 'uploads', 'files', 'storage'],
    relatedTo: ['UPLOADTHING_APP_ID'],
  },
  {
    name: 'UPLOADTHING_APP_ID',
    description: 'UploadThing application ID',
    category: 'storage',
    service: 'UploadThing',
    required: false,
    example: 'xxxxxxxxxxxx',
    keywords: ['uploadthing', 'app', 'uploads'],
    relatedTo: ['UPLOADTHING_SECRET'],
  },

  // ==================== Deployment & Hosting ====================
  {
    name: 'VERCEL_TOKEN',
    description: 'Vercel authentication token for deployments and API access',
    category: 'deployment',
    service: 'Vercel',
    required: false,
    example: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['vercel', 'deployment', 'hosting', 'ci/cd'],
    relatedTo: ['VERCEL_ORG_ID', 'VERCEL_PROJECT_ID'],
  },
  {
    name: 'VERCEL_ORG_ID',
    description: 'Vercel organization ID for team deployments',
    category: 'deployment',
    service: 'Vercel',
    required: false,
    example: 'team_xxxxxxxxxxxxxxxxxxxx',
    keywords: ['vercel', 'organization', 'team'],
    relatedTo: ['VERCEL_TOKEN'],
  },
  {
    name: 'VERCEL_PROJECT_ID',
    description: 'Vercel project ID for specific project deployments',
    category: 'deployment',
    service: 'Vercel',
    required: false,
    example: 'prj_xxxxxxxxxxxxxxxxxxxx',
    keywords: ['vercel', 'project', 'deployment'],
    relatedTo: ['VERCEL_TOKEN'],
  },
  {
    name: 'NETLIFY_AUTH_TOKEN',
    description: 'Netlify personal access token for API and deployments',
    category: 'deployment',
    service: 'Netlify',
    required: false,
    example: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['netlify', 'deployment', 'hosting', 'ci/cd'],
    relatedTo: ['NETLIFY_SITE_ID'],
  },
  {
    name: 'NETLIFY_SITE_ID',
    description: 'Netlify site ID for specific site deployments',
    category: 'deployment',
    service: 'Netlify',
    required: false,
    example: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
    keywords: ['netlify', 'site', 'deployment'],
    relatedTo: ['NETLIFY_AUTH_TOKEN'],
  },
  {
    name: 'CLOUDFLARE_API_TOKEN',
    description: 'Cloudflare API token for Workers, Pages, and DNS management',
    category: 'deployment',
    service: 'Cloudflare',
    required: false,
    example: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['cloudflare', 'workers', 'pages', 'dns', 'cdn'],
    relatedTo: ['CLOUDFLARE_ACCOUNT_ID'],
  },
  {
    name: 'CLOUDFLARE_ACCOUNT_ID',
    description: 'Cloudflare account ID for API operations',
    category: 'deployment',
    service: 'Cloudflare',
    required: false,
    example: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['cloudflare', 'account', 'api'],
    relatedTo: ['CLOUDFLARE_API_TOKEN'],
  },
  {
    name: 'RENDER_API_KEY',
    description: 'Render API key for deployment management',
    category: 'deployment',
    service: 'Render',
    required: false,
    example: 'rnd_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['render', 'deployment', 'hosting', 'ci/cd'],
    relatedTo: [],
  },
  {
    name: 'RAILWAY_TOKEN',
    description: 'Railway authentication token for deployments',
    category: 'deployment',
    service: 'Railway',
    required: false,
    example: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['railway', 'deployment', 'hosting', 'ci/cd'],
    relatedTo: [],
  },
  {
    name: 'FLY_API_TOKEN',
    description: 'Fly.io API token for edge deployments',
    category: 'deployment',
    service: 'Fly.io',
    required: false,
    example: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['fly', 'flyio', 'edge', 'deployment', 'hosting'],
    relatedTo: [],
  },
  {
    name: 'HEROKU_API_KEY',
    description: 'Heroku API key for deployments and app management',
    category: 'deployment',
    service: 'Heroku',
    required: false,
    example: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
    keywords: ['heroku', 'deployment', 'paas', 'hosting'],
    relatedTo: [],
  },
  {
    name: 'DOCKER_USERNAME',
    description: 'Docker Hub username for container registry',
    category: 'deployment',
    service: 'Docker',
    required: false,
    example: 'yourusername',
    keywords: ['docker', 'container', 'registry', 'hub'],
    relatedTo: ['DOCKER_PASSWORD'],
  },
  {
    name: 'DOCKER_PASSWORD',
    description: 'Docker Hub password or access token',
    category: 'deployment',
    service: 'Docker',
    required: false,
    example: 'dckr_pat_xxxxxxxxxxxxxxxxxxxx',
    keywords: ['docker', 'container', 'registry', 'authentication'],
    relatedTo: ['DOCKER_USERNAME'],
  },

  // ==================== Other Services ====================
  {
    name: 'GITHUB_TOKEN',
    description: 'GitHub personal access token for API operations',
    category: 'other',
    service: 'GitHub',
    required: false,
    example: 'ghp_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['github', 'git', 'api', 'repository', 'ci/cd'],
    relatedTo: [],
  },
  {
    name: 'GITHUB_CLIENT_ID',
    description: 'GitHub OAuth app client ID for authentication',
    category: 'auth',
    service: 'GitHub',
    required: false,
    example: 'Iv1.xxxxxxxxxxxxxxxxxxxx',
    keywords: ['github', 'oauth', 'authentication', 'login'],
    relatedTo: ['GITHUB_CLIENT_SECRET'],
  },
  {
    name: 'GITHUB_CLIENT_SECRET',
    description: 'GitHub OAuth app client secret',
    category: 'auth',
    service: 'GitHub',
    required: false,
    example: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['github', 'oauth', 'secret', 'authentication'],
    relatedTo: ['GITHUB_CLIENT_ID'],
  },
  {
    name: 'LINEAR_API_KEY',
    description: 'Linear API key for issue tracking integration',
    category: 'other',
    service: 'Linear',
    required: false,
    example: 'lin_api_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['linear', 'issues', 'project management', 'tracking'],
    relatedTo: [],
  },
  {
    name: 'AIRTABLE_API_KEY',
    description: 'Airtable personal access token for database API',
    category: 'other',
    service: 'Airtable',
    required: false,
    example: 'patxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    keywords: ['airtable', 'database', 'spreadsheet', 'api'],
    relatedTo: ['AIRTABLE_BASE_ID'],
  },
  {
    name: 'AIRTABLE_BASE_ID',
    description: 'Airtable base ID for specific database access',
    category: 'other',
    service: 'Airtable',
    required: false,
    example: 'appXXXXXXXXXXXXXXXX',
    keywords: ['airtable', 'base', 'database'],
    relatedTo: ['AIRTABLE_API_KEY'],
  },
  {
    name: 'ZAPIER_WEBHOOK_URL',
    description: 'Zapier webhook URL for automation triggers',
    category: 'other',
    service: 'Zapier',
    required: false,
    example: 'https://hooks.zapier.com/hooks/catch/xxxxx/xxxxx/',
    keywords: ['zapier', 'automation', 'webhook', 'integration'],
    relatedTo: [],
  },
  {
    name: 'MAKE_WEBHOOK_URL',
    description: 'Make (Integromat) webhook URL for automation',
    category: 'other',
    service: 'Make',
    required: false,
    example: 'https://hook.make.com/xxxxxxxxxxxxxxxxxxxxx',
    keywords: ['make', 'integromat', 'automation', 'webhook'],
    relatedTo: [],
  },
  {
    name: 'CRON_SECRET',
    description: 'Secret for authenticating cron job webhooks',
    category: 'other',
    service: 'Cron',
    required: false,
    example: 'your-secure-random-secret',
    keywords: ['cron', 'scheduled', 'jobs', 'webhook', 'security'],
    relatedTo: [],
  },
  {
    name: 'WEBHOOK_SECRET',
    description: 'Generic webhook signing secret for request verification',
    category: 'other',
    service: 'Webhooks',
    required: false,
    example: 'whsec_your-secure-secret',
    keywords: ['webhook', 'secret', 'security', 'verification'],
    relatedTo: [],
  },
  {
    name: 'NODE_ENV',
    description: 'Node.js environment mode (development, production, test)',
    category: 'other',
    service: 'Node.js',
    required: true,
    example: 'production',
    keywords: ['node', 'environment', 'mode', 'development', 'production'],
    relatedTo: [],
  },
  {
    name: 'APP_URL',
    description: 'Application base URL for callbacks and links',
    category: 'other',
    service: 'Application',
    required: true,
    example: 'https://yourdomain.com',
    keywords: ['url', 'application', 'base url', 'domain'],
    relatedTo: [],
  },
  {
    name: 'API_BASE_URL',
    description: 'API server base URL for client requests',
    category: 'other',
    service: 'Application',
    required: false,
    example: 'https://api.yourdomain.com',
    keywords: ['api', 'url', 'server', 'endpoint'],
    relatedTo: ['APP_URL'],
  },
];
